### ISSUE TITLE
无法加载插件

### ISSUE THREAD

**Issue by 1234-star** [oliverkirk-sudo/qchat_system_status#1]
系统：ubuntu22.04
部署：手动部署
报错[2023-08-27 14:55:57.737] host.py (96) - [ERROR] : 加载模块: plugins/qchat_system_status/main.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'cpuinfo'"), <traceback object at 0x7f7450295980>)

**Comment by 1234-star** [comment]
[2023-08-27 15:01:08.720] keymgr.py (78) - [INFO] : 使用api-key:default
[2023-08-27 15:01:08.724] manager.py (246) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-08-27 15:01:08.748] models.py (295) - [INFO] : 插件注册完成: n='SysStat', d='查看系统状态', v=0.1, a='RockChinQ' (<class 'plugins.SysStatPlugin.main.SysStatPlugin'>)
[2023-08-27 15:01:08.923] models.py (295) - [INFO] : 插件注册完成: n='Webwlkr', d='基于GPT的函数调用能力，为QChatGPT提供联网功能', v=0.1.1, a='RockChinQ' (<class 'plugins.WebwlkrPlugin.main.WebwlkrPlugin'>)
[2023-08-27 15:01:08.929] host.py (96) - [ERROR] : 加载模块: plugins/qchat_system_status/main.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'cpuinfo'"), <traceback object at 0x7fb850365fc0>)
Traceback (most recent call last):
  File "/home/ui1/3v/qgpt/QChatGPT/pkg/plugin/host.py", line 93, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ui1/3v/qgpt/QChatGPT/plugins/qchat_system_status/main.py", line 6, in <module>
    from plugins.qchat_system_status.pkg.system_test import drawstatus
  File "/home/ui1/3v/qgpt/QChatGPT/plugins/qchat_system_status/pkg/system_test.py", line 3, in <module>
    import cpuinfo
ModuleNotFoundError: No module named 'cpuinfo'
[2023-08-27 15:01:08.933] settings.py (98) - [INFO] : 已全局启用内容函数。
[2023-08-27 15:01:08.933] host.py (123) - [INFO] : 初始化插件
[2023-08-27 15:01:08.935] host.py (139) - [INFO] : 以下插件已初始化: Webwlkr, SysStat
2023-08-27 15:01:09 - INFO     [WebSocket] 成功登录到账号2728404354。
[2023-08-27 15:01:09.044] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号2728404354。
2023-08-27 15:01:09 - INFO     [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-08-27 15:01:09.044] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-08-27 15:01:20.948] main.py (298) - [INFO] : QQ: 2728404354, MAH: 127.0.0.1:8080
[2023-08-27 15:01:20.949] main.py (299) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37

**Comment by oliverkirk-sudo** [comment]
尝试更新

**Comment by 1234-star** [comment]
更新插件吗

**Comment by oliverkirk-sudo** [comment]
是的

**Comment by 1234-star** [comment]
更新插件报错
ERROR: Could not find a version that satisfies the requirement platform (from versions: none)
ERROR: No matching distribution found for platform

**Comment by 1234-star** [comment]
是依赖的问题吗

**Comment by oliverkirk-sudo** [comment]
那就手动安装一下requirements看看吧

**Comment by oliverkirk-sudo** [comment]
我使用的python版本是3.9

**Comment by 1234-star** [comment]
依赖装不上哈，估计可能我是3.10
i1@ser498294851897:~/3v/qgpt/QChatGPT/plugins/qchat_system_status$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psutil in /home/ui1/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (5.9.5)
ERROR: Could not find a version that satisfies the requirement platform (from versions: none)
ERROR: No matching distribution found for platform
ui1@ser498294851897:~/3v/qgpt/QChatGPT/plugins/qchat_system_status$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psutil in /home/ui1/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (5.9.5)
ERROR: Could not find a version that satisfies the requirement math (from versions: none)
ERROR: No matching distribution found for math

**Comment by oliverkirk-sudo** [comment]
这两个包都是python内置的，你只要安装一下py-cpuinfo就行

**Comment by 1234-star** [comment]
可以了，就是这个的问题，现在已经正常回复
